In [78]:
import numpy as np
import pandas as pd

In [86]:
columns = 8
rows = 8
base_array = np.array(
    [
        [735, np.nan, 45, np.nan, 125, np.nan, 167, np.nan],
        [np.nan for i in range(columns)],
        [450, np.nan, 337, np.nan, 95, np.nan, 245, np.nan],
        [np.nan for i in range(columns)],
        [124, np.nan, 430, np.nan, 230, np.nan, 460, np.nan],
        [np.nan for i in range(columns)],
        [75, np.nan, 20, np.nan, 32, np.nan, 20, np.nan],
        [np.nan for i in range(columns)],
    ]
)

In [87]:
mean_array = base_array.copy()
for i in range(rows):
    for j in range(columns):
        if np.isnan(mean_array[i][j]):
            if j > 0 and j + 1 < columns:
                mean_array[i][j] = (mean_array[i][j - 1] + mean_array[i][j + 1]) / 2

for i in range(rows):
    for j in range(columns):
        if np.isnan(mean_array[i][j]):
            if i > 0 and i + 1 < rows:
                mean_array[i][j] = (mean_array[i - 1][j] + mean_array[i + 1][j]) / 2

In [88]:
last_col = columns - 1
last_row = rows - 1
eps = 3
for i in range(rows):
    if i < 1:
        mean_array[i][last_col] = round((mean_array[i][last_col - 1] + mean_array[i + 1][last_col - 1]) / 2, eps)
    elif i >= 1 and i < last_row - 1:
        mean_array[i][last_col] = round((mean_array[i - 1][last_col - 1] + mean_array[i][last_col - 1] + mean_array[i + 1][last_col - 1]) / 3, eps)
    elif i == last_row - 1:
        mean_array[i][last_col] = round((mean_array[i - 1][last_col - 1] + mean_array[i][last_col - 1]) / 2, eps)

for j in range(columns):
    if j < 1:
        mean_array[last_row][j] = round((mean_array[last_row - 1][j] + mean_array[last_row - 1][j + 1]) / 2, eps)
    elif j >= 1 and j < last_col - 1:
        mean_array[last_row][j] = round((mean_array[last_row - 1][j - 1] + mean_array[last_row - 1][j] + mean_array[last_row - 1][j + 1]) / 3, eps)
    elif j == last_col - 1:
        mean_array[last_row][j] = round((mean_array[last_row - 1][j - 1] + mean_array[last_row - 1][j]) / 2, eps)

mean_array[last_row][last_col] = mean_array[last_row - 1][last_col - 1]

In [89]:
mean_array

array([[735.   , 390.   ,  45.   ,  85.   , 125.   , 146.   , 167.   ,
        186.5  ],
       [592.5  , 391.75 , 191.   , 150.5  , 110.   , 158.   , 206.   ,
        206.   ],
       [450.   , 393.5  , 337.   , 216.   ,  95.   , 170.   , 245.   ,
        267.833],
       [287.   , 335.25 , 383.5  , 273.   , 162.5  , 257.5  , 352.5  ,
        352.5  ],
       [124.   , 277.   , 430.   , 330.   , 230.   , 345.   , 460.   ,
        350.833],
       [ 99.5  , 162.25 , 225.   , 178.   , 131.   , 185.5  , 240.   ,
        240.   ],
       [ 75.   ,  47.5  ,  20.   ,  26.   ,  32.   ,  26.   ,  20.   ,
        130.   ],
       [ 61.25 ,  47.5  ,  31.167,  26.   ,  28.   ,  26.   ,  23.   ,
         20.   ]])

In [90]:
for i in mean_array:
    print(' '.join([str(j) for j in i]))

735.0 390.0 45.0 85.0 125.0 146.0 167.0 186.5
592.5 391.75 191.0 150.5 110.0 158.0 206.0 206.0
450.0 393.5 337.0 216.0 95.0 170.0 245.0 267.833
287.0 335.25 383.5 273.0 162.5 257.5 352.5 352.5
124.0 277.0 430.0 330.0 230.0 345.0 460.0 350.833
99.5 162.25 225.0 178.0 131.0 185.5 240.0 240.0
75.0 47.5 20.0 26.0 32.0 26.0 20.0 130.0
61.25 47.5 31.167 26.0 28.0 26.0 23.0 20.0


In [91]:
df = pd.DataFrame(data=mean_array)
df.to_excel('result.xlsx')

In [94]:
obr_array = mean_array.copy()
obr_array[-1] = [np.nan for i in range(columns)]
for i in range(rows):
    obr_array[i][-1] = np.nan
obr_array

array([[735.  , 390.  ,  45.  ,  85.  , 125.  , 146.  , 167.  ,    nan],
       [592.5 , 391.75, 191.  , 150.5 , 110.  , 158.  , 206.  ,    nan],
       [450.  , 393.5 , 337.  , 216.  ,  95.  , 170.  , 245.  ,    nan],
       [287.  , 335.25, 383.5 , 273.  , 162.5 , 257.5 , 352.5 ,    nan],
       [124.  , 277.  , 430.  , 330.  , 230.  , 345.  , 460.  ,    nan],
       [ 99.5 , 162.25, 225.  , 178.  , 131.  , 185.5 , 240.  ,    nan],
       [ 75.  ,  47.5 ,  20.  ,  26.  ,  32.  ,  26.  ,  20.  ,    nan],
       [   nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan]])

In [ ]:
# last_col
# last_row

In [157]:
def inv_dist_extr(array, row, col, radius):
    sum_z = 0
    sum_inv_dist = 0
    # print(f'------{row}:{col}-------')
    for i in range(rows - 1):
        for j in range(columns - 1):
            dist = (((row - i) ** 2) + ((col - j) ** 2)) ** 0.5
            if dist <= radius:
                # print(array[i][j], dist)
                sum_inv_dist += 1 / dist
                sum_z += obr_array[i][j] / dist
    if sum_inv_dist == 0:
        return 0
    else:
        return sum_z / sum_inv_dist

In [162]:
R = 3
for row in range(rows):
    obr_array[row][last_col] = round(inv_dist_extr(obr_array, row, last_col, R), 2)
for col in range(columns):
    obr_array[last_row][col] = round(inv_dist_extr(obr_array, last_row, col, R), 2)

obr_array

array([[735.  , 390.  ,  45.  ,  85.  , 125.  , 146.  , 167.  , 176.24],
       [592.5 , 391.75, 191.  , 150.5 , 110.  , 158.  , 206.  , 202.92],
       [450.  , 393.5 , 337.  , 216.  ,  95.  , 170.  , 245.  , 243.13],
       [287.  , 335.25, 383.5 , 273.  , 162.5 , 257.5 , 352.5 , 275.99],
       [124.  , 277.  , 430.  , 330.  , 230.  , 345.  , 460.  , 263.61],
       [ 99.5 , 162.25, 225.  , 178.  , 131.  , 185.5 , 240.  , 228.7 ],
       [ 75.  ,  47.5 ,  20.  ,  26.  ,  32.  ,  26.  ,  20.  , 164.72],
       [ 95.22, 102.74, 106.09, 100.43,  96.77, 103.38, 120.18, 101.62]])

In [159]:
df = pd.DataFrame(data=obr_array)
df.to_excel('result.xlsx')